version: '3.8'

services:
  ghost-studio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - SKIP_BUILD_ERRORS=true
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  cloudflared-gsa:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_GSA_TUNNEL_TOKEN}
    volumes:
      - ./cloudflared/gsa:/etc/cloudflared:ro
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      ghost-studio:
        condition: service_healthy

  cloudflared-n8n:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_N8N_TUNNEL_TOKEN}
    volumes:
      - ./cloudflared/n8n:/etc/cloudflared:ro
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - n8n

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    env_file:
      - .env.production
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  n8n_data:
    driver: local