[build]
  command = "CI=false yarn build"
  publish = ".next"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SHARP_PATH = "/tmp/node_modules/sharp"
  NODE_ENV = "production"
  SKIP_PRETTIER = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@next/env", "firebase-admin"]
  included_files = ["database.rules.json"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[build.processing]
  skip_processing = false

[dev]
  framework = "#auto"
  targetPort = 3000
  port = 8888
  publish = "public"
  autoLaunch = true