tunnel: ${CLOUDFLARE_N8N_TUNNEL_ID}
credentials-file: /cloudflared/creds.json
originCert: /cloudflared/cert.pem

ingress:
  - hostname: n8ntest.ghoststudioacademy.store
    service: http://n8n:5678
  - service: http_status:404