tunnel: ${CLOUDFLARE_TUNNEL_GSA_ID}
credentials-file: /cloudflared/creds.json
originCert: /cloudflared/cert.pem

ingress:
  - hostname: ghoststudioacademy.store
    service: http://ghost-studio:3000
  - service: http_status:404