model:
  name: phi-2
  path: /models/phi-2
  quantization: int8  # For better performance on limited RAM
  
server:
  host: 0.0.0.0
  port: 8000
  workers: 1

generation:
  max_new_tokens: 512
  temperature: 0.7
  top_p: 0.9